#!/bin/bash
# 简单的硬件启动脚本

echo "无ROM硬件启动步骤："
echo ""
echo "1. 连接JTAG调试器"
echo "   - 连接JTAG接口到芯片"
echo "   - 确保调试器驱动已安装"
echo ""
echo "2. 启动OpenOCD"
echo "   openocd -f interface/ftdi/olimex-arm-usb-ocd.cfg -f target/riscv32.cfg"
echo ""
echo "3. 在另一个终端连接GDB"
echo "   riscv32-unknown-elf-gdb program.elf"
echo "   (gdb) target remote localhost:3333"
echo "   (gdb) load"
echo "   (gdb) set \$pc = 0x10000"
echo "   (gdb) continue"
echo ""
echo "或者使用一键加载："
echo "   openocd -f interface/ftdi/olimex-arm-usb-ocd.cfg \\"
echo "           -f target/riscv32.cfg \\"
echo "           -c 'init' \\"
echo "           -c 'halt' \\"
echo "           -c 'load_image program.bin 0x10000' \\"
echo "           -c 'reg pc 0x10000' \\"
echo "           -c 'resume' \\"
echo "           -c 'exit'"
