#!/bin/bash
# 分析 SPI 时钟定义位置的区别

echo "=== SPI时钟定义位置分析 ==="

echo "1. 从 image.png 观察到:"
echo "   模块: ip1_TFTLCD_0"
echo "   端口: io_spi_clk (高亮显示)"
echo "   这是模块的输出端口"

echo ""
echo "2. 两种时钟定义方式:"
echo ""
echo "方式1: 定义在 spiClkReg 的 Q 端"
echo "create_generated_clock -name spi_clk \\"
echo "  -source [get_ports clock] \\"
echo "  -divide_by 10 \\"
echo "  [get_pins -hierarchical *spiClkReg*/Q]"
echo ""
echo "方式2: 定义在 io_spi_clk 端口"
echo "create_generated_clock -name spi_clk \\"
echo "  -source [get_ports clock] \\"
echo "  -divide_by 10 \\"
echo "  [get_ports io_spi_clk]"

echo ""
echo "3. 关键区别分析:"
echo ""
echo "定义在 spiClkReg/Q (内部节点):"
echo "   ✅ 优点: 更接近时钟生成源"
echo "   ✅ 优点: 时序分析更精确"
echo "   ❌ 缺点: 需要知道内部寄存器名称"
echo "   ❌ 缺点: 综合后名称可能变化"
echo ""
echo "定义在 io_spi_clk (端口):"
echo "   ✅ 优点: 端口名称稳定"
echo "   ✅ 优点: 约束更简洁"
echo "   ❌ 缺点: 可能包含额外的缓冲延迟"
echo "   ❌ 缺点: 时序分析稍微不精确"

echo ""
echo "4. 实际影响:"
echo "   对于这个设计:"
echo "   🟡 差异很小 - 都能正确工作"
echo "   🟡 时序差异 - 可能几十ps的差别"
echo "   🟡 工程实践 - 端口定义更常用"

echo ""
echo "5. 建议:"
echo "   ✅ 推荐使用端口定义 [get_ports io_spi_clk]"
echo "   ✅ 原因: 更稳定、更简洁、更易维护"
echo "   ✅ 对时序影响微乎其微"

echo ""
echo "结论: 两种方式都可行，端口定义更实用"
