// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vasic_soc_tb.cpp"
#include "Vasic_soc_tb___024root__0.cpp"
#include "Vasic_soc_tb__Trace__0.cpp"
#include "Vasic_soc_tb__ConstPool_0.cpp"
#include "Vasic_soc_tb___024root__Slow.cpp"
#include "Vasic_soc_tb___024root__0__Slow.cpp"
#include "Vasic_soc_tb__Syms.cpp"
#include "Vasic_soc_tb__Trace__0__Slow.cpp"
#include "Vasic_soc_tb__TraceDecls__0__Slow.cpp"
