#!/bin/bash
# 详细对比分析两个约束文件

echo "=== 约束文件详细问题分析 ==="

echo "1. 端口定义对比:"
echo ""
echo "ip1_SimpleEdgeAiSoC 实际端口 (来自RTL):"
echo "  input  clock, reset"
echo "  output io_uart_tx"  
echo "  input  io_uart_rx"
echo "  output [31:0] io_gpio_out"
echo "  input  [31:0] io_gpio_in"
echo "  output io_lcd_spi_clk, io_lcd_spi_mosi, ..."
echo ""

echo "ip1_timing.sdc (正确):"
echo "  ✅ [get_ports clock]  - 实际存在"
echo "  ✅ [get_ports reset]  - 实际存在"
echo "  ✅ 仅约束端口，不约束内部信号"
echo ""

echo "timing_complete.sdc (问题):"
echo "  ❌ [get_ports io_uart_rx]    - 这是输出端口，不应设input_delay"
echo "  ❌ [get_ports io_uart_tx_irq] - 这不是端口，是内部信号"
echo "  ❌ [get_ports io_gpio_in*]    - 端口名是io_gpio_in，不是io_gpio_in*"
echo "  ❌ [get_ports io_lcd_spi_*]   - 这些是输出端口，不应设input_delay"

echo ""
echo "2. 约束方向错误:"
echo ""
echo "timing_complete.sdc 的方向错误:"
echo "  ❌ io_uart_rx 是INPUT端口，却在某处被当作OUTPUT约束"
echo "  ❌ io_uart_tx 是OUTPUT端口，却在某处被当作INPUT约束"
echo "  ❌ io_gpio_out 是OUTPUT端口，不应有input_delay"
echo "  ❌ io_lcd_spi_* 都是OUTPUT端口，不应有input_delay"

echo ""
echo "3. 约束逻辑错误:"
echo ""
echo "timing_complete.sdc 错误假设:"
echo "  ❌ 认为可以对所有信号设置I/O约束"
echo "  ❌ 不区分输入输出方向"
echo "  ❌ 将内部信号当作端口"
echo "  ❌ 过度约束不必要的信号"

echo ""
echo "ip1_timing.sdc 正确做法:"
echo "  ✅ 仅约束时钟和复位"
echo "  ✅ 使用假路径处理特殊信号"
echo "  ✅ 不对I/O信号过度约束"
echo "  ✅ 基于实际RTL结构"

echo ""
echo "4. 实际影响评估:"
echo "  timing_complete.sdc 会导致:"
echo "  🔴 约束语法错误 - 方向不匹配"
echo "  🔴 工具警告/错误 - 端口不存在"
echo "  🔴 约束失效 - 大部分I/O约束无效"
echo "  🔴 时序分析不准确"
